---
- name: generate docker-compose
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ traefik_docker_compose }}/docker-compose.yaml"

- name: create docker network
  community.docker.docker_network:
    name: "{{ traefik_docker_network }}"
    driver: "{{ traefik_docker_network_driver }}"
    driver_options: "{{ traefik_docker_network_driver_options }}"
    state: present

- name: pull docker image
  community.docker.docker_image:
    name: "{{ traefik_docker_image }}"
    source: pull

- name: traefik docker start
  community.docker.docker_compose:
    state: present
    project_src: "{{ traefik_docker_compose }}"
