---
- name: generate docker-compose
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ traefik_docker_compose }}/docker-compose.yaml"

- name: create docker networks
  community.docker.docker_network:
    name: "{{ network.name }}"
    driver: "{{ network.driver }}"
    driver_options: "{{ network.driver_opts }}"
    state: present
  loop: "{{ traefik_docker_networks }}"
  loop_control:
    loop_var: network

- name: pull docker image
  community.docker.docker_image:
    name: "{{ traefik_docker_image }}"
    source: pull

- name: traefik docker start
  community.docker.docker_compose:
    state: present
    project_src: "{{ traefik_docker_compose }}"
