---
- name: include install tasks
  import_tasks: "install-{{ traefik_install }}.yaml"

- name: create config directory
  file:
    dest: "{{ traefik_config_dir }}"
    state: directory

- name: generate config
  ansible.builtin.template:
    src: traefik.toml.j2
    dest: "{{ traefik_config_dir }}/traefik.toml"
  notify: traefik docker restart

- name: include config tasks
  import_tasks: "config-{{ traefik_install }}.yaml"
