---
- name: set real paths
  set_fact:
    traefik_real_config_dir: "{{ traefik_config_dir }}"
    traefik_real_provider_file_directory: "{{ traefik_provider_file_directory }}"
    traefik_real_tls_certificate_dir: "{{ traefik_tls_certificate_dir }}"
    traefik_real_log_dir: "{{ traefik_log_dir }}"

- name: create config/log directories
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_real_config_dir }}"
    - "{{ traefik_real_provider_file_directory }}"
    - "{{ traefik_real_tls_certificate_dir }}"
    - "{{ traefik_real_log_dir }}"

- name: include install tasks
  include_tasks: "install-{{ traefik_install }}.yaml"
